### ISSUE TITLE
Hi, I'm Ariel and i want to contribute

### ISSUE THREAD

**Issue by arielzv** [prog-o-meter/prog-o-meter#101]
Hi,
I'm new to git but not to python / tk. 
I'll like to contribute, on any issue you think fits, I hope i won't need a lot of help with git.

also I've encountered few issues, I'm not sure if you already have open tickets for:
(I'm using windows, python 2.7).
1. first when running prog-o-meter.py i had this issue

>  Traceback (most recent call last):
>   File "C:\Users\Ariel\Documents\GitHub\prog-o-meter\prog-o-meter.py", line 18, in <module>
>     from congratulations.Congratulations import Congratulations
>    ImportError: No module named congratulations.Congratulations
> 

  so I created an empty file called "__init__.py" file in congratulations folder, that fixed this issue.
  https://docs.python.org/3/tutorial/modules.html#packages

2. urllib.parse

> Traceback (most recent call last):
>   File "C:\Users\Ariel\Documents\GitHub\prog-o-meter\prog-o-meter.py", line 18, in <module>
>     from congratulations.Congratulations import Congratulations
>   File "C:\Users\Ariel\Documents\GitHub\prog-o-meter\congratulations\Congratulations.py", line 2, in <module>
>     from urllib.parse import quote
> ImportError: No module named parse

urllib.parse only exists on python 3, on python 2 you can use urllib.quote directly.

3. days shows as 0x instead of just x:
![days](https://user-images.githubusercontent.com/17690217/40889779-36d0c3c8-6775-11e8-89ac-77ed3d7d146a.jpg)

4. when you finish and log on again, the date on the message  will be one date before the correct date.

5. X(Quit) button doesn't work properly.
instead of just exiting the tk window (and ending the program), the tk screen freezes and I get a kill-confirmation screen from python ide.

![image](https://user-images.githubusercontent.com/17690217/40889992-086d9756-6778-11e8-98ac-d4c1a00a8234.png)

SO..
I'll be happy to start my github journey with this project, it seems like a good team and I'll be happy to tackle everything you need me to.

Ariel

**Comment by lineaba** [comment]
Hey, welcome to the team it is nice to have you join. I will look more thoroughly through the issues you mentioned as soon as I can, but I see you are running python 2.7. 
We have switched, and are only supporting python 3.x. Would you mind testing if you get the same issues when using python3?
Also, just to make sure, I believe our documentation says we run python3, but if you ran into documentation that said we were using python 2.7, I might have missed updating that in certain places. If you let me know where, then I can update it.

**Comment by d3giigii** [comment]
Hello Ariel, 

Welcome to the project and Git as a whole. Being someone with previous Python and Tk experience I'm sure there will be a lot you can contribute. 

Regarding the issues you mentioned... 
1. I'm almost certain this is because you're running Python 2.7 (thanks for including that info btw). I'd recommend running with Python 3+ and seeing if this resolves itself. 
2. Definitely because you're running Python 2.7. 
3. Never noticed that. This seems like something that may be fixed using datetime or relevant formatting options. If not a little bit of string manipulation should do the trick. 
4. After testing for myself I noticed a couple things... 
    - The date is actually incorrect from the beginning, and 
    - the _**value**_ of the date of completion updates when clicking the "1 more day" button, but the sentence does not update with the new value until "1 more day" is clicked again (still resulting in an incorrect date), or until the program is re-launched and the sentence updates (with the date value). 
5. Strange... Does this happen when you run it both inside **and** outside your IDE? This seems like a rather low-level issue; It wouldn't surprise me if running with Python 3+ fixed this as well. If not more information would help (OS info, debug output, etc...). 

While Python 2 is supported; most contributors are developing with Python 3+ convention so it would be a good idea to run prog-o-meter with Python 3+ as well.

If you would like to start working on 3 and 4 say so in this thread and you should be added to the list of assignee's for this issue (which means no one else should be making a similar fix). In the future it is a good idea too only have one issue per thread, but since this 3 and 4 are both relatively simple, and this is also an introduction; I think you will be good to work on them together. 

If you have any other questions feel free to "@" myself below; otherwise lineaba should get back to you in this thread within the next few days.

**Comment by arielzv** [comment]
Hi,
I'll be happy to work on #3 and #4.
Linea - user_guide.md says you are supporting python 3, about that I'm sure that in the future we can make it support python 2 with a few adjastments. Linux/mac users get python 2.7 as the default python.
Thanks!

**Comment by d3giigii** [comment]
@lineaba My bad, I'll remember that for the future.

**Comment by arielzv** [comment]
@lineaba issues 1,2,5 fixed when using python 3.
I think I solved issues 3,4 
you are welcome to check the pull requests.

Thanks

**Comment by lineaba** [comment]
great about issue 1, 2, 5. 
I will check the PR as soon as I can, but it may be a few days, as school is getting close to finals and I am getting busy. Sorry about that.
